name:                wumpus-hunter-server
version:             0.1.0.0
github:              "benjaminjenkins1/langstudy-wumpus"
license:             MIT
author:              "Benjamin Jenkins and Elijah Johnson"
maintainer:          "benjamin.jenkins1@marist.edu"
copyright:           "2018 Benjamin Jenkins"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/wumpus-hunter-server#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.1
- json
- http-server >= 1.0.6
- network-uri >= 2.6.1
- utf8-string
- HTTP

library:
  source-dirs: src

executables:
  wumpus-hunter-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wumpus-hunter-server

tests:
  wumpus-hunter-server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wumpus-hunter-server
